#  Black Cards Against Humanity cards to be drawn by the Card Czar
#
#  Blanks should be indicated by a sequence of exactly five underscores.
#  The number of blanks correspond to the number of white cards to be played.
#  If no blanks, one white card is expected per answer.

module.exports = [
  "(Pick 3) I went from _____ to _____, all thanks to _____.",
  "(Pick 3) _____ + _____ = _____",
  "(Pick 2) An international tribunal has found _____ guilty of _____.",
  "(Pick 2) An the Academy Award for _____ goes to _____.",
  "(Pick 2) Before _____, all we had was_____.",
  "(Pick 2) Dear Sir or Madam, We regret to inform you that the office of _____ has denied your request for _____.",
  "(Pick 2) For my next trick, I will pull _____ out of _____.",
  "(Pick 2) I never truly understood _____ until I encountered _____.",
  "(Pick 2) I spent my whole life working toward _____, only to have it ruined by _____.",
  "(Pick 2) If God didn't want us to enjoy _____, he wouldn't have given us _____.",
  "(Pick 2) In M. Night Shamalan's new movie, Bruce Willis discovers that _____ had really been _____ all along."
  "(Pick 2) In a pinch, _____ can be a suitable substitute for _____.",
  "(Pick 2) In a world ravaged by _____, our only solace is _____.",
  "(Pick 2) Lifetime presents _____, the story of _____.",
  "(Pick 2) Michael Bay's new three-hour action epic pits _____ against _____.",
  "(Pick 2) Rumor has it that Vladimir Putin's favorite dish is _____ stuffed with _____.",
  "(Pick 2) Step 1: _____. Step 2: _____. Step 3: Profit.",
  "(Pick 2) That's right I killed _____. How you ask? _____.",
  "(Pick 2) What's the next superhero/sidekick duo?",
  "(Pick 2) When I was tripping on acid _____ turned into _____.",
  "(Pick 2) You haven't truly lived until you've experienced _____ and _____ at the same time.",
  "(Pick 2) _____ is a slippery slope that leads to _____.",
  "(Pick 2) _____ would be woefully incomplete without _____.",
  "(Pick 2) After months of practice with _____, I think I'm finally ready for _____.",
  "(Pick 2) With enough time and pressure, _____ will turn into _____.",
  "(Pick 2) _____: Hours of fun. Easy to use. Perfect for _____!",
  "(Pick 2) When you get right down to it, _____ is just _____.",
  "A romantic candlelit dinner would be incomplete without _____.",
  "A successful job interview begins with a firm handshake and ends with _____.",
  "After blacking out during New Year's Eve, I was awoken by _____.",
  "After months of debate, the Occupy Wall Street General Assembly could only agree on “More _____!”",
  "After the earthquake, Sean Penn brought _____ to the people of Haiti.",
  "Alternative medicine is now embracing the curative powers of _____.",
  "And I would have gotten away with it, too, if it hadn't been for _____.",
  "And what did you bring for show and tell?",
  "Anthropologists have recently discovered a primitive tribe that worships _____.",
  "As part of his contract, Prince won't perform without _____ in his dressing room.",
  "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _____.",
  "BILLY MAYS HERE FOR _____.",
  "Before I run for president, I must destroy all evidence of my involvement with _____.",
  "But before I kill you, Mr. Bond, I must show you _____.",
  "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate _____ in the workplace.",
  "Charades was ruined for me forever when my mom had to act out _____.",
  "Coming to Broadway this season, _____: The Musical.",
  "Dear Abby, I'm having some trouble with ______ and would like your advice.",
  "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _____.",
  "During high school I never really fit in until I found _____ club.",
  "During his midlife crisis, my dad got really into _____.",
  "During sex, I like to think about _____.",
  "Every Christmas my uncle gets drunk and tells the story about _____.",
  "Everyone down on the ground! We don't want to hurt anyone. We're just here for _____.",
  "Finally! A service that delivers _____ right to your door.",
  "Having problems with _____? Try _____!",
  "He who controls _____ controls the world.",
  "Hey baby, come back to my place and I'll show you _____.",
  "How am I maintaining my relationship status.",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.",
  "I drink to forget _____.",
  "I got 99 problems but _____ ain't one.",
  "I learned the hard way that you can't cheer up a grieving friend with _____.",
  "I'm not like the rest of you. I'm too rich and busy for _____.",
  "I'm sorry professor, but I couldn't complete my homework because of _____.",
  "In 1,000 years when paper money is but a distant memory, _____ will be our currency.",
  "In L.A. county Jail, word is you can trade 200 cigarettes for _____.",
  "In Michael Jackson's final moments, he thought about _____.",
  "In Rome, there are whisperings that the Vatican has a secret room devoted to _____.",
  "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _____.",
  "In his new self-produced album, Kanye West raps over the sounds of _____.",
  "In his newest and most difficult stunt, David Blaine must escape from _____.",
  "In its new tourism campaign, Detroit proclaims that it has finally eliminated _____.",
  "In the distant future, historians will agree that _____ marked the beginning of America's decline.",
  "In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time.",
  "In the seventh circle of Hell, sinners must endure _____ for all eternity.",
  "Instead of coal, Santa now gives the bad children _____ .",
  "It's a pity that kids these days are all getting involved with _____.",
  "Jesus is _____.",
  "Life for American Indians was forever changed when the White Man introduced them to _____.",
  "Listen, son. If you want to get involved with _____, I won't stop you. Just steer clear of _____.",
  "Little Miss Muffet, Sat on a tuffet, Eating her curds and _____.",
  "Loving you is easy 'cause you're _____.",
  "MTV's new reality show features eight washed-up celebrities living with _____.",
  "Major League Baseball has banned _____ for giving players an unfair advantage.",
  "Maybe she's born with it. Maybe it's _____.",
  "Members of New York's social elite are paying thousands of dollars just to experience _____.",
  "Money can't buy me love, but it can buy me _____.",
  "My country, 'tis of thee, sweet land of _____.",
  "My gym teacher got fired for adding _____ to the obstacle course.",
  "My life is ruled by a vicious cycle of _____ and _____.",
  "My mom freaked out when she looked at my browser history and found _____.com.",
  "My new favorite porn star is Joey “_____” McGee.",
  "Next from J.K. Rowling: Harry Potter and the Chamber of _____.",
  "Next on ESPN2: The World Series of _____.",
  "Next time on Dr. Phil: How to talk to your child about _____.",
  "On the third day of Christmas, my true love game to me: three French hens, two turtle doves, and _____.",
  "Only two things in life are certain: death and _____.",
  "Science will never explain the origin of _____.",
  "Studies show that lab rats navigate mazes 50% faster after being exposed to _____",
  "TSA guidelines now prohibit _____ on airplanes.",
  "The CIA now interrogates enemy agents by repeatedly subjecting them to _____.",
  "The Five Stages of Grief: denial, anger, bargaining, _____, acceptance.",
  "The blind date was going horribly until we discovered our shared interest in _____.",
  "The class field trip was completely ruined by _____.",
  "The healing process began when I joined a support group for victims of _____.",
  "The socialist governments of Scandanavia have declared that access to – is a basic human right.",
  "The votes are in, and the new high school mascot is _____.",
  "This holiday season, Tim Allen must overcome his fear of _____ to save Christmas.",
  "This is the way the world ends This is the way the world ends Not with a bang but with _____.",
  "This is your captain speaking. Fasten your seatbelts and prepare for _____.",
  "This month's Cosmo: 'Spice up your sex life by bringing ______ into the bedroom.'",
  "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only _____ and his wits.",
  "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of _____.",
  "Tonight on 20/20: What you don't know about _____ could kill you.",
  "Turns out that _____-Man was neither the hero we needed nor wanted.",
  "Wake up, America. Christmas is under attack by secular liberals and their _____.",
  "War! What is it good for?",
  "What am I giving up for Lent?",
  "What are my parents hiding from me?",
  "What brought the orgy to a grinding halt?",
  "What did I bring back from Mexico?",
  "What did Vin Diesel eat for dinner?",
  "What did the US airdrop to the children of Afghanistan?",
  "What do old people smell like?",
  "What does Dick Cheney prefer?",
  "What don't you want to find in your Chinese food?",
  "What ended my last relationship?",
  "What gets better with age?",
  "What gives me uncontrollable gas?",
  "What has been making life difficult at the nudist colony?",
  "What helps Obama unwind?",
  "What is Batman's guilty pleasure?",
  "What keeps me warm during the cold, cold winter?",
  "What left this stain on my couch?",
  "What never fails to liven up the party?",
  "White people like _____.",
  "What will I bring back in time to convince people that I am a powerful wizard?",
  "What will always get you laid?",
  "What would grandma find disturbing, yet oddly charming?",
  "What's Teach for America using to inspire inner city students to succeed?",
  "What's a girl's best friend?",
  "What's my anti-drug?",
  "What's my secret power?",
  "What's that smell?",
  "What's that sound?",
  "What's the crustiest?",
  "What's the gift that keeps on giving?",
  "What's the most emo?",
  "What's the new fad diet?",
  "What's the next Happy Meal toy?",
  "What's there a ton of in heaven?",
  "When I am President of the United States, I will create the Department of _____.",
  "When I am a billionaire, I shall erect a 50-foot statue to commemorate _____.",
  "When I pooped, what came out of my butt?",
  "When Pharaoh remained unmoved, Moses called down a Plague of _____.",
  "When all else fails, I can always masturbate to _____.",
  "When the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____.",
  "Why am I sticky?",
  "Why can't I sleep at night?",
  "Why do I hurt all over?",
  "_____. kid tested mother approved.",
  "_____. Awesome in theory, kind of a mess in practice.",
  "_____. Betcha can't have just one.",
  "_____. High five bro.",
  "_____. It's a trap!",
  "_____. That's how I want to die.",
  "_____: good to the last drop.",
  "_____? There's an app for that.",
]
